<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<Version>2.0.0</Version>
		<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
		<Company>Technitium</Company>
		<Product>Technitium DNS Server</Product>
		<Authors>Zafer Balkan</Authors>
		<AssemblyName>MispConnectorApp</AssemblyName>
		<RootNamespace>MispConnector</RootNamespace>
		<PackageProjectUrl>https://technitium.com/dns/</PackageProjectUrl>
		<RepositoryUrl>https://github.com/TechnitiumSoftware/DnsServer</RepositoryUrl>
		<Description>Block malicious domain names pulled from MISP feeds.\n\nNote! This app works independent of the DNS server's built-in blocking feature. The options configured in DNS server Settings section does not apply to this app.</Description>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<OutputType>Library</OutputType>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\upstream\DnsServer\DnsServerCore.ApplicationCommon\DnsServerCore.ApplicationCommon.csproj" />
	  <ProjectReference Include="..\upstream\TechnitiumLibrary\TechnitiumLibrary.Net\TechnitiumLibrary.Net.csproj" />
	  <ProjectReference Include="..\upstream\TechnitiumLibrary\TechnitiumLibrary\TechnitiumLibrary.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="dnsApp.config">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
